baseURL: /
languageCode: nl-nl
title: Voorstelling Hartstocht | Music by Usia
theme: roxo
summarylength: 25
defaultContentLanguage: nl

languages:
  nl:
    title: Music by Usia
    description: Something
    weight: 1

menu:
  nav:
    - name: Home
      url: ''
      weight: 1
    - name: Muziek
      url: muziek
      weight: 2
    - name: Agenda
      url: agenda
      weight: 3
    - name: Over mij
      url: over-mij
      weight: 4
    - name: Doneer
      url: doneer
      weight: 5
    - name: Blog
      url: blog
      weight: 6
    - name: Contact
      url: contact
      weight: 7

params:
  logo: images/logo.png
  dateFormat: 26 FEB 1994
  description: Roxo Hugo themes | Design Agency Template by StaticMania
  author: StaticMania
  googleAnalitycsID: Your ID
  formspreeFormUrl: 'https://formspree.io/myykjpje'

  contactForm:
    placeholder_first_name: First Name
    placeholder_last_name: Last Name
    placeholder_email: Email
    placeholder_project_type: Project Type
    placeholder_about_the_project: About the Project
    send_message: Send Message
    projectType:
      - value: gd
        title: Graphics Design
      - value: wd
        title: Web Design
  navAction:
    status: true
    name: Get in touch
    url: contact
  banner:
    enable: true
    background_image: images/backgrounds/hero-background.jpg
    heading: We’re a Design Studio That Belies In the Great Ideas
    tagline: 'WE WORK HARD, WE PLAY HARD'
    primary_button: See Our Works
    primary_button_url: portfolio
    secondary_button: Connect with Us
    secondary_button_url: contact
  muziek:
    enable: true
    title: OUR RECENT WORKS
    subtitle: Crafting experiences and seeking to make the complex clear & beautiful.
  call_to_action:
    enable: true
    background_image: images/backgrounds/cta-background.jpg
    title: LET’S WORK TOGETHER
    primary_button: Submit Query
    primary_button_url: contact
    secondary_button: Not Convinced
    secondary_button_url: portfolio
  footer:
    contactInfo:
      title: Contact Info
      address: '713 Elmwood St.<br>Prior Lake, MN 55372'
      phone: 409-896-1444
      email: info@roxo.co
    sitemap:
      title: Sitemap
      link:
        - name: About Company
          url: about
        - name: Projects
          url: portfolio
        - name: Blog
          url: blog
        - name: Contact
          url: contact
    social:
      title: Social Media
      link:
        - name: Medium
          url: '#'
        - name: Behance
          url: '#'
        - name: Dribbble
          url: '#'
        - name: Instagram
          url: '#'
    service:
      title: 'We help brands:'
      description: >-
        develop design solutions<br>produce valuable cultural content<br>create
        fresh brand experience

deployment:
  order:
    - .jpg$
    - .gif$
  targets:
    - name: voorstellinghartstocht.nl - s3
      URL: 's3://voorstellinghartstocht.nl?region=eu-central-1'
      exclude: 'deploy.sh,misc/**'
  matchers:
    - pattern: ^.+\.(js|css|svg|ttf)$
      cacheControl: 'max-age=31536000, no-transform, public'
      gzip: true
    - pattern: ^.+\.(png|jpg)$
      cacheControl: 'max-age=31536000, no-transform, public'
      gzip: false
    - pattern: ^sitemap\.xml$
      contentType: application/xml
      gzip: true
    - pattern: ^.+\.(html|xml|json)$
      gzip: true
